b2k:
  host: http://localhost:8081
  zone: local-zone
  team:
    key: local-team-key
  gcp-project:
    name: local-gcp-project-name
    environment: dev

quarkus:
  application:
    name: finden-backend
    version: local
  package:
    jar:
      enabled: true
      type: fast-jar
  http:
    port: ${PORT:8081}
    cors:
      enabled: true
    enable-compression: true
  devservices:
    enabled: false
  log:
    json:
      console:
        enable: false
      additional-field:
        serviceName:
          value: "${quarkus.application.name}"
        environment:
          value: "${quarkus.profile:dev}"
  micrometer:
    export:
      stackdriver:
        enabled: false
        projectId: ${b2k.gcp-project.name}
        resourceType: generic_node
  mongodb:
    database: "finden"
    connect-timeout: PT5S
    server-selection-timeout: PT5S
    credentials:
      auth-source: admin
  index-dependency:
    mu-kotlin-logging:
      group-id: "io.github.microutils"
      artifact-id: "kotlin-logging-jvm"

"%dev":
  quarkus:
    application:
      name: local-finden-backend
  mongodb:
    connection-string: mongodb://localhost:27017

"%test":
  b2k:
    testing:
      integration:
        use-testcontainers: true
  quarkus:
    application:
      name: test-finden-backend
      version: test
    mongodb:
      database: "finden-test"
