b2k:
  host: http://localhost:8081
  zone: local-zone
  team:
    key: local-team-key
  gcp-project:
    name: local-gcp-project-name
    environment: dev

quarkus:
  application:
    name: finden-backend
    version: local
  package:
    jar:
      enabled: true
      type: fast-jar
  http:
    port: ${PORT:8081}
    cors: true
  resteasy:
    gzip:
      enabled: true
  log:
    console:
      json:
        ~: false
        fields:
          level:
            enabled: false
          message:
            enabled: false
          stack-trace:
            enabled: false
          logger-class-name:
            enabled: false
          logger-name:
            enabled: false
  micrometer:
    export:
      stackdriver:
        enabled: false
        projectId: ${b2k.gcp-project.name}
        resourceType: generic_node
  mongodb:
    database: "finden"
    connect-timeout: PT5S
    server-selection-timeout: PT5S
    credentials:
      auth-source: admin

"%dev":
  quarkus:
    application:
      name: local-finden-backend
    devservices:
      enabled: false
  mongodb:
    connection-string: mongodb://localhost:27017

"%test":
  b2k:
    testing:
      integration:
        use-testcontainers: true
  quarkus:
    application:
      name: test-finden-backend
      version: test
    devservices:
      enabled: false
    mongodb:
      database: "finden-test"
