###
GET http://localhost:8081/api/finden/produkte

###
GET http://localhost:8081/api/finden/produkte?limit=2&include=20003012%2C97479%2C20002385

###
GET http://localhost:8081/api/finden/produkte?include=20003012%2C97479%2C20002385

###
GET http://localhost:8081/api/finden/produkte?preis=15

###
GET http://localhost:8081/api/finden/produkte?include=20003012%2C97479%2C20002385&exclude=20002385

###
GET http://localhost:8081/api/finden/produkte?klassifikation3=24&exclude=20002854&preis=23

###
GET http://localhost:8081/api/finden/produkte?test=test&limit=1
